name: Build

on:
  pull_request:
  push:
    branches:
    - master
    tags:
    - '[0-9]+.[0-9]+.[0-9]+-?*'

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - shell: bash
      run: |
        git fetch --prune --unshallow

    - name: Setup Dotnet 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.402'

    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100-rc.1.20452.10'

    - name: pack
      run: |
        dotnet pack --configuration Release --output ./packages \
          /p:NoWarn=NU5105 \
          /p:RepositoryUrl=https://github.com/thefringeninja/Transacto.Tasks \
          /p:RepositoryType=git


    - name: push
      run: |
        dotnet tool restore
        find ./packages -name "*.nupkg" | xargs -n1 dotnet tool run gpr -- push --api-key=${{ secrets.github_token }}
      if: github.event_name == 'push'
