name: Build

on:
  pull_request:
  push:
    branches:
    - master
    tags:
    - '[0-9]+.[0-9]+.[0-9]+-?*'

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0

    - uses: actions/setup-dotnet@v1.3.0
      with:
        dotnet-version: '3.1.100'

    - name: build
      run: dotnet build --configuration Release

    - name: pack
      run: dotnet pack --configuration Release --output ./packages

    - name: push
      run: |
        for f in ./packages/*.nupkg
        do
          curl -vX PUT -u "thefringeninja:${{ secrets.GITHUB_TOKEN }}" -F package=@$f https://nuget.pkg.github.com/thefringeninja/
        done
      if: github.event_name == 'push'
